# Generated by Django 4.2.7 on 2023-12-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='movies',
            new_name='produtos',
        ),
    ]
