# Generated by Django 4.2.5 on 2023-12-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_remove_local_horário_remove_local_produtos'),
        ('produtos', '0004_rename_movies_list_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Local',
        ),
        migrations.AddField(
            model_name='produto',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='local.local'),
        ),
    ]
