# Generated by Django 4.2.5 on 2023-12-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0013_remove_local_produtos'),
        ('produtos', '0006_alter_produto_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='local.local'),
        ),
    ]
