# Generated by Django 4.2.5 on 2023-12-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0015_local_produtos'),
        ('produtos', '0007_alter_produto_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='local.local'),
        ),
    ]
