# Generated by Django 4.2.5 on 2023-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_produto_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='poster_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
