# Generated by Django 4.2.5 on 2023-12-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensagenParaSuporte',
            new_name='MensagemParaSuporte',
        ),
    ]
