# Generated by Django 4.2.5 on 2023-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='nome do local na base de dados'),
        ),
    ]
