# Generated by Django 4.2.5 on 2023-12-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_local_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='CEP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='descrição',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='endereço',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='imagem',
            field=models.ImageField(null=True, upload_to='local/imagens_de_locais'),
        ),
        migrations.AlterField(
            model_name='local',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude do local'),
        ),
        migrations.AlterField(
            model_name='local',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude do local'),
        ),
        migrations.AlterField(
            model_name='local',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
