# Generated by Django 4.2.5 on 2023-12-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_local_cep_local_descrição_local_endereço_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='descrição',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
