# Generated by Django 4.2.5 on 2023-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_alter_local_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagem',
            field=models.ImageField(null=True, upload_to='imagens_de_locais/'),
        ),
    ]
