# Generated by Django 4.2.5 on 2023-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_movies_list_produtos'),
        ('local', '0007_alter_local_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='horário',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='produtos',
            field=models.ManyToManyField(to='produtos.produto'),
        ),
    ]
