# Generated by Django 4.2.5 on 2023-12-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0008_local_horário_local_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='horário',
        ),
        migrations.RemoveField(
            model_name='local',
            name='produtos',
        ),
    ]
