# Generated by Django 4.2.5 on 2023-12-07 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produto_local_produto_local'),
        ('local', '0009_remove_local_horário_remove_local_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='produtos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_produtos', to='produtos.produto'),
        ),
    ]
