# Generated by Django 4.2.5 on 2023-12-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_local'),
        ('local', '0010_local_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='produtos',
        ),
        migrations.AddField(
            model_name='local',
            name='produtos',
            field=models.ManyToManyField(null=True, related_name='all_produtos', to='produtos.produto'),
        ),
    ]
