# Generated by Django 4.2.5 on 2023-12-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_local'),
        ('local', '0011_remove_local_produtos_local_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='produtos',
            field=models.ManyToManyField(related_name='all_produtos', to='produtos.produto'),
        ),
    ]
