# Generated by Django 4.2.5 on 2023-12-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0012_alter_local_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='produtos',
        ),
    ]
