# Generated by Django 4.2.5 on 2023-12-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0013_remove_local_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
