# Generated by Django 4.2.5 on 2023-12-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_local'),
        ('local', '0014_local_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='produtos',
            field=models.ManyToManyField(null=True, related_name='produtos_do_local', to='produtos.produto'),
        ),
    ]
