# Generated by Django 4.2.5 on 2023-12-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_poster_url'),
        ('local', '0015_local_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, related_name='produtos_do_local', to='produtos.produto'),
        ),
    ]
