# Generated by Django 4.2.5 on 2023-12-04 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_local_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HermesUser',
            new_name='PerfilUsuario',
        ),
    ]
